// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:68ba5dfd-b1fa-46f2-a939-ca205069d1c2',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'rnauthstarter-hosting-mobilehub-2123157420',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2lv811brvu96j.cloudfront.net',
    'aws_mobile_analytics_app_id': 'bd06d399897245e788b12efe260aa987',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e3b8e63e-1753-11e8-b7ec-1579a7b87ac8',
    'aws_project_name': 'RNAuthStarter',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'rnauthstarter-mobilehub-2123157420',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_MUZcHDCE8',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '2mc3gpni4ia5ru5tddp7enesun',
}

export default awsmobile;
